
server:
  port: 8077

  tomcat:
    max-threads: 128
    min-spare-threads: 5
    uri-encoding: UTF-8
  servlet:
    # 项目contextPath
    context-path: /zzboot
    session:
      cookie:
        http-only: false
        secure: false

spring:
  http:
    encoding:
      charset: UTF-8
  messages:
    encoding: UTF-8
  profiles:
    active: dev
  resources:
    chain:
      strategy:
        content:
          #资源名-md5
          enabled: true
      cache: true

  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 100MB

    #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000



  jackson:
    time-zone: GMT+8

  cache:
    type: ehcache


  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 0
    password:



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5 #格式要求不严谨
    encoding: UTF-8
    cache: false
    servlet:
      content-type:  text/html

  main:
    allow-bean-definition-overriding: true




#mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.**.domain;com.**.entity;com.**.bo
  global-config:
    #刷新mapper 调试神器
    db-config:
      db-type: mysql
  configuration:
    #驼峰下划线转换#驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false



thread:
  pool:
    keepAliveSeconds: 2000
    maxPoolSize: 100
    corePoolSize: 10



#Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login/toLogin
    # 权限认证失败地址
    unauthorizedUrl: /error/unauth
    # 首页地址
    indexUrl: /main/home
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    cacheName: shiro-activeSessionCache


zzboot:
  ossEngine: FILESYSTEM


#
#jwt:
#  header: Authorization
#  secret: mySecret
#  # token 过期时间 2个小时
#  expiration: 7200000
#  auth:
#    # 授权路径
#    path: /login
#    # 获取用户信息
#    account: /info
#
