
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

spring:
  http:
    encoding:
      charset: UTF-8
  messages:
    encoding: UTF-8
  profiles:
    active: dev
  resources:
    chain:
      strategy:
        content:
          #资源名-md5
          enabled: true
      cache: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 0
    password:


  cache:
    ehcache:
      config: 'classpath:ehcache.xml'



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type:  text/html

  main:
    allow-bean-definition-overriding: true




#------------------------------------------#
#                                          #
#            mybatis plus 配置              #
#                                          #
#------------------------------------------#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml;classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.**.domain;com.**.entity;com.**.bo
  global-config:
    #刷新mapper 调试神器
    db-config:
      db-type: mysql
  configuration:
    #驼峰下划线转换#驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false


